/**
 * Piotr Dobiech 316625
 */

#pragma once

#define CONNECTIONS_QUEUE_SIZE 16

#define CONNECTION_RECEIVE_BUFFER_SIZE 4096

#define CONNECTION_TIMEOUT_SECONDS 1
#define CONNECTION_TIMEOUT_MICROSECONDS 0

#define PARSER_LINE_BUFFER_SIZE 128
